# Generated by Django 4.0.6 on 2022-07-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
