# Generated by Django 4.0.6 on 2022-07-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_orderproduct_remove_order_user_order_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
