# Generated by Django 4.0.6 on 2022-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_remove_order_note1_alter_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('W przygotowaniu', 'W przygotowaniu'), ('Zamówiono', 'Zamówiono'), ('Dostarczono', 'Dostarczono')], max_length=200, null=True),
        ),
    ]
